### ISSUE TITLE
Cannot execute defined funk

### ISSUE THREAD

**Issue by NiekPas** [bbugyi200/funky#128]
Using `funky 3.0.1`, I cannot seem to get funks working:

`$ funky -a fu`

**fu.zaxxxx00.sh**
`echo 'hello world'`

`$ funky`

`> fu() { echo 'hello world' "$@"; }`

`$ fu`

`> fu: command not found`

**Comment by bbugyi200** [comment]
Thanks for reporting this. It sounds like maybe the shell hasn't been integrated? Did you follow the steps in the [Additional Install Steps] section?

[Additional Install Steps]: https://github.com/bbugyi200/funky#additional-installation-steps

**Comment by NiekPas** [comment]
I was under the impression that was only required when building from source, sorry about that.

The `_source_globals()` and `_source_locals` functions in `~/.local/share/funky/funky.zsh` give me the following error:

`bash: /usr/bin/funky: No such file or directory`

Which I can confirm do not exist.

BTW, I assumed bash was supported (#33), is that correct?

**Comment by NiekPas** [comment]
Just saw your updated comment. Output of `which funky`:

`/home/niek-pas/.local/bin/funky`

**Comment by bbugyi200** [comment]
@NiekPas Sorry. I actually removed bash support a while back (see these [release notes]). This project has very recently gaining some traction, however, so I am working to restore bash support. Back when I decided to stop supporting bash, I was the only one using this. And I couldn't exactly argue with my only customer right?

Anyway. It shouldn't be hard to bring support back. I opened up #129 to trash my progress. I'll be sure to tag you when its fixed.

As for the other issue (the `No such file or directory` message) that looks like a legitamite bug. It should be fixed with e0cd7ae32b4 though.

**Comment by bbugyi200** [comment]
@NiekPas Okay. Funky should once again work with Bash. 

I'm gonna close this issue, but let me know if you have any problems.

**Comment by NiekPas** [comment]
Okay, this seems to be working again! One thing that might be of note is that I had to manually pull `funky.sh` and save it to `~/.local/share/funky/funky.sh` to get it working -- should I open a new issue for this?

**Comment by bbugyi200** [comment]
@NiekPas May as well use a new issue in case it turns out to be useful to reference. I already created it though, so no need to create another. See #131.
